# Generated by Django 5.2.8 on 2026-01-07 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_exchangerate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
