# Generated by Django 6.0 on 2026-01-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('pago_movil', 'Pago Móvil'), ('zelle', 'Zelle'), ('paypal', 'PayPal'), ('cashea', 'Cashea'), ('transferencia', 'Transferencia Bancaria')], max_length=20, null=True),
        ),
    ]
